name: Build Wasm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 rust 工具链
        # uses: actions-rs/toolchain@v1
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip1

      - name: 构建 Release 版本
        run: |
            cargo fetch
            cargo update
            # cargo build --target wasm32-wasip1 --release --verbose
            cargo build --release

      - name: 安装 Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 安装 tree-sitter cli
        run: npm install -g tree-sitter-cli

      - name: 安装 emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "latest"

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: 生成 wasm
        working-directory: languages/cangjie
        run: |
          tree-sitter generate
          tree-sitter build --wasm

      - name: 打包
        run: |
          mkdir -p package/grammars
          mkdir -p package/languages/cangjie

          cp target/wasm32-wasip1/release/*.wasm package/extension.wasm
          cp extension.toml package/

          cp languages/cangjie/*.wasm package/grammars/

          rsync -av --exclude='grammar.js' languages/cangjie/ package/languages/cangjie/

      - name: 生成 zip 文件
        run: |
          cd package
          zip -r ../extension-package.zip .

      - name: 上传 zip 文件
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: extension-package.zip
